baseurl = "https://innovacion.social/"
languageCode = "es-es"
title = "Innovación Social Podcast"
theme = "castanet"
#canonifyurls = false
buildFuture = false
buildDrafts = false
googleAnalytics = ""
themesdir = "./themes"
paginate = "9"


[permalinks]
	# page = "/:filename/"
	about = "/:filename/"
	episode = "/:filename/"

# The theme supports menus with up to one submenu per menu item
# The menu name must be "Main"
# The menus are sorted based upon their identifier
[[Menu.Main]]
    name = "Acerca de"
    identifier = "about"
    url = "/about"

[[Menu.Main]]
    name = "Contacto"
    identifier = "contact"
    url = "/contact"

[[Menu.Main]]
    name = "Anfitriones"
    identifier = "hosts"
    url = "/host"

[[Menu.Main]]
    name = "Invitados"
    identifier = "guests"
    url = "/guest"

[[Menu.Main]]
    name = "Recursos"
    identifier = "resources"
    url = "#!"
[[Menu.Main]]
    name = "Artículos"
    identifier = "articles"
    url = "/articles/"
    parent = "resources"
[[Menu.Main]]
    name = "Libros"
    identifier = "books"
    url = "/books/"
    parent = "resources"


[params]
mainSections = ["episode"]
site_theme = "innosoc"
#site_layout = "grid"
site_layout = "row"
enable_jumbo = "true"
# enable_jumbo = "false"
# truncate = "100"
about_logo = "../img/logo_innovacion_social.png"
favicon = "icon/favicon_innovacion_social.png"
copyright_notice = "Copyright 2019-2020 [Innovación Social Podcast](https://innovacion.social)"
itunes_subscribe = "https://podcasts.apple.com/es/podcast/innovaci%C3%B3n-social-podcast/id1499626298"
#android_subscribe = "http://subscribeonandroid.com/feeds.podtrac.com/VGAulpN7MY1U"
#spotify_subscribe = "https://open.spotify.com/show/..."
#google_play_subscribe = "https://goo.gl/app/playmusic?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&link=https://play.google.com/music/m/Ihj4yege3lfmp3vs5yoopgxijpi?t%3DArrested_DevOps"
#stitcher_subscribe = "http://www.stitcher.com/podcast/arrested-devops-2/arrested-devops"
#soundcloud_subscribe = "http://feeds.soundcloud.com/users/soundcloud:users:203144248/sounds.rss"
#pocketcasts_subscribe = "http://pcasts.in/feed/feeds.soundcloud.com/users/soundcloud:users:203144248/sounds.rss"
#mailchimp_subscribe = "//arresteddevops.us3.list-manage.com/subscribe/post?u=5e4cbcac996bb9df25f970a89&amp;id=154fa76bcc"
ivoox_susbcribe = "https://www.ivoox.com/innovacion-social-podcast_nq_689486_1.html"
rss_subscribe = "https://innovacionsocial.libsyn.com/rss" #only set this if you don't want to use the built-in feed
description = "Innovacion Social Podcast te acerca las últimas novedades de los proyectos que te inspiran"
media_prefix = "http://traffic.libsyn.com/innovacionsocial/"
disqusShortname = ""
  [params.feed]
    copyright = "Copyright 2019-2020 Innovación Social Podcast" #do not use markdown in this field; it is used in the feed
    itunes_subtitle = "El mejor podcast para conocer los proyectos que cambian el mundo" #no markdown or HTML
    itunes_author = "Cecilia Güemes y César García" #no markdown or HTML
    itunes_summary = "The HugoCast is the best podcast you've ever seen. You will learn everything you ever needed to know about podcasting from the most inspiring experts to ever show up on the whole internet." # Limited to 4000 characters or less, plain text, no HTML
    itunes_owner_name = "Innovación Social"
    itunes_owner_email = "info@innovacion.social" #contains the e-mail address that will be used to contact the owner of the Podcast for communication specifically about their Podcast on iTunes. It will not be publicly displayed on iTunes.
    itunes_image = "https://innovacion.social.png" #fqdn to the image art for your podcast
    itunes_top_category = "Culture"
    itunes_first_sub_category = "Education"
    itunes_second_sub_category = "News"
    language = "es-es"

#  [params.podlove] # https://subscribe-button.podlove.org
#    subscribe_title = "Subscríbete"              # fallback: site title from above
#    subscribe_subtitle = ""           # fallback: ""
#    subscribe_description = ""        # fallback: ""
#    subscribe_cover = "img/logo.jpg"  # fallback: ""
#    subscribe_color = "#585e6c"       # fallback: ""
#    subscribe_size = "medium"         # options: small, medium, big
#    subscribe_format = "rectangle"    # options: rectangle, square, cover
#    subscribe_style = "filled"        # options: filled, outline, frameless
#    subscribe_language = "es"         # options: nl (dutch), en (english), eo (esperanto), de (german), fi (finnish), fr (french), ja (french)
#    subscribe_feed_type = "audio"     # options: audio, video
#    subscribe_feed_format = "mp3"     # options: mp3, aac, ogg, opus

  [params.social]
  #  github = "innovacion.social"
  #  gitlab = "mattstratton"
    facebook = "Innovacion.Social.podcast"
    facebook_admin = ["500557137","1234"] # This needs to be one or more page admins to get domain insights
    twitter = "Innova_social"
    twitter_domain = "innovacion.social" # This domain shows in twitter cards as "View on `twitter_domain`"
 #   googleplus = "ArrestedDevOps"
 #   pinterest = "nozzleio"
    instagram = "Innovacion.Social.podcast"
    tiktok = "InnovacionSocial"
 #   youtube = "arresteddevops"
 #   linkedin = "mattstratton"

  [params.authors]
    [params.authors.Cecilia]
      name	= "Cecilia Güemes"
      thumbnail = "img/host/cecilia_guemes.jpg"
      bio = "Cecilia es experta en Innovación Social"
      [params.authors.Cecilia.social]
        facebook = "ceciliaguemes"
        twitter = "ceciliaguemes"
        linkedin = "mattstratton"
        instagram = "ceciliaguemes"
	homepage = "https://www.ceciliaguemes.com"


    [params.authors.Cesar]
      name = "César García"
      thumbnail = "img/host/cesar_garcia.jpg"
      bio = "César es experto en Innovación Social"
      [params.authors.Cesar.social]
         facebook = "cesargarcia"
	 twitter = "elsatch"
	 linkedin = "cesargarciasaez"
	 github = "elsatch"
	 youtube = "lahoramaker"
         homepage = "https://www.cesargarciasaez.com"